import './../styles/globals.css'
import Navigation from "./../Components/Navigation";
import Head from "next/head";
import Footer from "./../Components/Footer";
import React from "react";
import {AppProps} from "next/app";

function PianoApp({Component, pageProps}: AppProps) {

    return (
        <>

            <Head>
                <title>Pianos Prelude</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="./favicon.png"/>
            </Head>

            <div className="flex justify-center py-8 bg-[#E3E7EC] min-h-screen">
                <div className="">

                    <Navigation/>

                    <h1>TITRE</h1>

                    <main className=" pl-12 pr-12">
                        <Component {...pageProps} />
                    </main>

                    <Footer/>

                </div>
            </div>

        </>
    )
}

export default PianoApp;
